#!/bin/bash
# CLI Demo: ZIGChain Asset Registry — Full Toolchain
# Generated by /cli-demo on 2026-03-18
set -e

cd "$(dirname "$0")/.."
source .venv/bin/activate

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   ZIGChain Asset Registry — CLI Demo                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

sleep 1

# ──────────────────────────────────────────────────────────────
# 1. Repository Overview
# ──────────────────────────────────────────────────────────────
echo "📁 Repository structure:"
echo ""
echo "assets/          — Asset JSON files (native, factory, IBC)"
echo "models/          — Pydantic validation models"
echo "schemas/         — Auto-generated JSON schemas"
echo "scripts/         — CLI tools for validation, generation, import"
echo ""

sleep 1

echo "📊 Asset counts:"
echo "  Native:  $(find assets/native -name '*.json' 2>/dev/null | wc -l) files"
echo "  Factory: $(find assets/factory -name '*.json' 2>/dev/null | wc -l) files"
echo "  IBC:     $(find assets/ibc -name '*.json' 2>/dev/null | wc -l) files"
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 2. View a sample asset (native ZIG token)
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 1: Inspect a native asset ━━━"
echo ""
echo "$ cat assets/native/zig.mainnet.json | python3 -m json.tool | head -25"
cat assets/native/zig.mainnet.json | python3 -m json.tool | head -25
echo "  ..."
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 3. Validate all assets (happy path)
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 2: Validate all 3,000+ assets ━━━"
echo ""
echo "$ python3 scripts/validate_assets.py --repo-root ."
python3 scripts/validate_assets.py --repo-root . 2>&1 | grep -E "(✅|Protection|Error)" | head -5
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 4. Validate mainnet only
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 3: Validate mainnet-only assets ━━━"
echo ""
echo "$ python3 scripts/validate_assets.py --repo-root . --network mainnet"
python3 scripts/validate_assets.py --repo-root . --network mainnet 2>&1 | grep -E "(✅|Protection|Error)" | head -5
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 5. Generate JSON schemas from Pydantic models
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 4: Generate JSON schemas ━━━"
echo ""
echo "$ python3 scripts/generate_schemas.py"
python3 scripts/generate_schemas.py
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 6. Generate chain-registry output (local only)
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 5: Generate Cosmos chain-registry artifacts ━━━"
echo ""
echo "$ python3 scripts/generate_chain_registry.py --skip-sync --out /tmp/chain-registry-demo"
python3 scripts/generate_chain_registry.py --skip-sync --out /tmp/chain-registry-demo 2>&1 | tail -10
echo ""
echo "Generated files:"
find /tmp/chain-registry-demo -name '*.json' -type f 2>/dev/null | head -6
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 7. Run strictness audit
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 6: Audit assets against strict validation rules ━━━"
echo ""
echo "$ python3 scripts/audit_strictness.py"
python3 scripts/audit_strictness.py
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 8. Run model unit tests
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 7: Run model unit tests ━━━"
echo ""
echo "$ python3 -m pytest models/tests/ -v --tb=short 2>&1 | tail -20"
python3 -m pytest models/tests/ -v --tb=short 2>&1 | tail -20
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 9. Edge case: validate with --warn-only (protected assets)
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 8: Validate with --warn-only (protected assets as warnings) ━━━"
echo ""
echo "$ python3 scripts/validate_assets.py --repo-root . --warn-only 2>&1 | grep -E '(Protection|✅)'"
python3 scripts/validate_assets.py --repo-root . --warn-only 2>&1 | grep -E "(Protection|✅)"
echo ""

sleep 2

# ──────────────────────────────────────────────────────────────
# 10. Edge case: generate with unverified assets included (local debug)
# ──────────────────────────────────────────────────────────────
echo "━━━ Step 9: Generate chain-registry including unverified assets (debug) ━━━"
echo ""
echo "$ python3 scripts/generate_chain_registry.py --skip-sync --include-unverified --out /tmp/chain-registry-debug"
python3 scripts/generate_chain_registry.py --skip-sync --include-unverified --out /tmp/chain-registry-debug 2>&1 | tail -5
echo ""

sleep 1

# ──────────────────────────────────────────────────────────────
# Done
# ──────────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   ✅ CLI Demo Complete                                     ║"
echo "║                                                            ║"
echo "║   Scripts demonstrated:                                    ║"
echo "║     • validate_assets.py (full, filtered, warn-only)      ║"
echo "║     • generate_schemas.py                                  ║"
echo "║     • generate_chain_registry.py (default, --include-unverified) ║"
echo "║     • audit_strictness.py                                  ║"
echo "║     • pytest model tests                                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
